import Foundation
import Observation

/// Cross-step container for the Add-Server wizard.
///
/// Why a reference-typed `@Observable` class instead of a pile of `@State`
/// value-types: ref doc §11 ("EphemeralSetupState"). SwiftUI's `@State`
/// mutations commit asynchronously, so when a `navigationDestination` closure
/// later reads back values the wizard just wrote it can see stale data. A
/// shared reference type sidesteps the race: mutations land instantly and
/// every view holding the same instance sees the new value.
///
/// All fields are initialised to safe empty/defaulted values so the state
/// object can be constructed up-front and incrementally populated as the user
/// progresses through the steps. None of these values survive the sheet being
/// dismissed — that's intentional (the name "ephemeral"). On success, the
/// final `Server` is persisted via SwiftData and the wizard drops the state.
///
/// Concurrency: `@Observable` classes are not inherently `Sendable`, and this
/// one isn't meant to be — it's only ever touched from the main actor by
/// SwiftUI views. Background work (SSH connect, installer stream) pulls out
/// the primitives it needs and never captures the state object.
@Observable
final class EphemeralSetupState {

    // MARK: - Connection form (step 1)

    /// Display name. If the user leaves it blank we fall back to `host` when
    /// we build the `Server`.
    var name: String = ""
    var host: String = ""
    /// Stored as a string so the text field can be validated lazily and show
    /// inline errors without juggling `Int?` bindings.
    var portText: String = "22"
    var sshUsername: String = "ubuntu"
    /// Auth method the user picked on the form. Drives which branch
    /// `AuthDetailView` renders.
    var authMethod: Server.AuthMethod = .password

    // MARK: - Password path (step 2a)

    /// Populated if the user chose `.password`.
    var sshPassword: String = ""
    /// Whether to save `sshPassword` to the Keychain on completion.
    var savePasswordToKeychain: Bool = true

    // MARK: - Key path (step 2b)

    /// Raw PEM text as the user pasted or imported it. Persisted back to the
    /// Keychain on completion when `useAppWideKey == false`.
    var importedPEM: String = ""
    /// Optional passphrase the user supplied for an encrypted PEM. Not
    /// persisted — we decrypt once, store the decrypted representation
    /// implicitly via `parsedKey`, and throw the passphrase away.
    var keyPassphrase: String = ""
    /// Result of `SSHKeyService.parsePrivateKey(pem:passphrase:)`. Nil until
    /// the user taps "Verify & Continue" in `AuthDetailView`.
    var parsedKey: SSHKeyService.ParsedKey?
    /// Optional user-supplied comment; defaults to a sane one when we write
    /// the key to the Keychain.
    var keyComment: String = ""
    /// Default key-auth mode: PocketTop uses its app-wide Ed25519 keypair
    /// (generated once and stored under `KeychainService.sshAppKeyAccount`).
    /// The wizard displays the public half for the user to copy into
    /// `~/.ssh/authorized_keys`. Flip to `false` to switch to bring-your-own
    /// private-key (PEM paste / file import).
    var useAppWideKey: Bool = true
    /// When `true` on the key path, we save `importedPEM` to Keychain under
    /// `sshAppKeyAccount` AND record that account on the `Server` row — so a
    /// future add-server flow can offer "Use app-wide key" prefilled.
    var saveKeyAsAppWide: Bool = false
    /// OpenSSH public-key line for the generated app-wide key. Populated once
    /// the key has been loaded or freshly generated by `AuthDetailView`.
    /// `nil` while still loading or when using an imported key.
    var generatedPublicLine: String?
    /// `SHA256:…` fingerprint of `generatedPublicLine` for the UI to show
    /// alongside the copy block so the user can verify on the server.
    var generatedPublicFingerprint: String?

    // MARK: - Host fingerprint (step 3)

    /// The `HostKeyInfo.fingerprint` captured during the initial SSH
    /// handshake. User confirms this in `HostFingerprintView` before we
    /// persist it onto `Server.sshHostKeyFingerprint`.
    var pendingHostFingerprint: String = ""

    // MARK: - Sudo (step 4)

    /// Populated only on the non-root branch; passed to
    /// `InstallerService.install(sudoPassword:)`.
    var sudoPassword: String = ""
    /// Persist `sudoPassword` to the Keychain with biometry protection on
    /// success. Default on — ref doc §8 says the whole point of gating sudo
    /// with biometry is that users don't have to retype it for upgrades.
    var saveSudoWithBiometry: Bool = true
    /// Cached from the first SSH handshake so the nav logic can skip the
    /// sudo step when the SSH user is already root.
    var sshUserIsRoot: Bool = false

    // MARK: - Install (step 5) → Done (step 6)

    /// Result of a successful install. Populated in `InstallProgressView` on
    /// the final `.step(name: "verified", …)` event, then consumed by the
    /// main-actor finaliser that creates & persists the `Server`.
    var connectionDetails: ConnectionDetails?

    /// The persisted `Server` once step 5 completes — `DoneView` reads the
    /// name/host off this for its success summary, and `AddServerFlow`
    /// includes it in the `.serverSetupComplete` notification.
    var server: Server?

    // MARK: - Derived / helpers

    /// Parsed port. `nil` when the text is empty or not a valid 1..65535 int.
    var port: Int? {
        guard let n = Int(portText), (1...65_535).contains(n) else { return nil }
        return n
    }

    /// Whether the step-1 form is fully valid. Drives the "Continue" button.
    var connectionFormIsValid: Bool {
        !host.trimmingCharacters(in: .whitespaces).isEmpty
            && port != nil
            && !sshUsername.trimmingCharacters(in: .whitespaces).isEmpty
    }

    /// Display name to use when building the `Server`. Falls back to `host`
    /// when the user leaves the Name field blank.
    var effectiveName: String {
        let trimmed = name.trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? host : trimmed
    }

    /// Reset key-path fields when the user changes auth method back to
    /// password mid-flow. Prevents stale `parsedKey` values from confusing
    /// later steps.
    func resetKeyFields() {
        importedPEM = ""
        keyPassphrase = ""
        parsedKey = nil
        keyComment = ""
        useAppWideKey = true
        saveKeyAsAppWide = false
        generatedPublicLine = nil
        generatedPublicFingerprint = nil
    }

    /// Reset password-path fields symmetrically.
    func resetPasswordFields() {
        sshPassword = ""
        savePasswordToKeychain = true
    }
}
